[package]
name = "let_clone"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Declarative macro to clone multiple values at once"
categories = ["rust-patterns"]
repository = "https://github.com/qthree/let_clone"

[lib]
doctest = false

[dependencies]

